import React, { useState, useEffect } from 'react';
import TransporterMasterView from './TransporterMasterView';

/**
 * GRNForm - 5.0 Goods Receipt Note (GRN) Module
 * Three-Level Hierarchy:
 *   Level 1: GRN Header (Multi-PO linking for same vendor, Transporter, Invoices)
 *   Level 2: Bale Cards (Generated by count, Live length sums)
 *   Level 3: Pieces within Bale (Generated by count on typing, No spinners, Multi-quality)
 * Validations:
 *   - Same vendor restriction across multi-selected POs
 *   - Sum of pieces must match declared total
 *   - Buffer tolerance check & Admin variance justification flag
 *   - Independent "Save Header" and Draft Save & Resume
 */
export default function GRNForm({
  grn,
  purchaseOrders = [],
  fabrics = [],
  transporters = [],
  onBack,
  onSaveGRN
}) {
  const isExisting = Boolean(grn && grn.id);

  // Level 1: Header State
  const [formData, setFormData] = useState({
    id: grn?.id || `GRN-${String(Math.floor(1000 + Math.random() * 9000))}`,
    date: grn?.date || new Date().toISOString().split('T')[0],
    linkedPOs: grn?.linkedPOs || (purchaseOrders[0] ? [purchaseOrders[0].id] : []),
    vendorId: grn?.vendorId || purchaseOrders[0]?.vendorId || '',
    vendorName: grn?.vendorName || purchaseOrders[0]?.vendorName || '',
    transporterId: grn?.transporterId || transporters[0]?.id || '',
    transporterName: grn?.transporterName || transporters[0]?.name || '',
    vendorInvoiceNo: grn?.vendorInvoiceNo || 'MST/1360/26-27',
    vendorInvoiceDate: grn?.vendorInvoiceDate || '2026-09-01',
    vendorChallanNo: grn?.vendorChallanNo || '1360',
    vendorChallanDate: grn?.vendorChallanDate || '2026-09-01',
    totalBales: grn?.totalBales || 5,
    declaredTotalMeters: grn?.declaredTotalMeters || 10415.25,
    status: grn?.status || 'Bale Entry in Progress', // Draft / Header Saved / Bale Entry in Progress / Completed
    adminApprovalNeeded: grn?.adminApprovalNeeded || false,
    adminJustification: grn?.adminJustification || '',
    bales: grn?.bales || []
  });

  const [showInlineTransporterModal, setShowInlineTransporterModal] = useState(false);
  // Filter POs: Only POs that are 'Sent' or 'Partially Received' (ready for Goods Receipt)
  const availablePOs = purchaseOrders.filter(
    (p) => p.status === 'Sent' || p.status === 'Partially Received' || formData.linkedPOs.includes(p.id)
  );

  // When PO selection changes, ensure all selected POs share the same vendor (8.3)
  const handleTogglePO = (poId) => {
    const selectedPO = purchaseOrders.find((p) => p.id === poId);
    if (!selectedPO) return;

    if (formData.linkedPOs.includes(poId)) {
      if (formData.linkedPOs.length === 1) {
        alert('At least one Purchase Order must remain linked.');
        return;
      }
      setFormData((prev) => ({
        ...prev,
        linkedPOs: prev.linkedPOs.filter((id) => id !== poId)
      }));
    } else {
      // 8.3 Check: Must share the same vendor!
      if (formData.vendorId && selectedPO.vendorId !== formData.vendorId) {
        alert(
          `Cannot link PO from different vendor. Selected PO belongs to ${selectedPO.vendorName}, but GRN vendor is ${formData.vendorName}.`
        );
        return;
      }

      setFormData((prev) => ({
        ...prev,
        linkedPOs: [...prev.linkedPOs, poId],
        vendorId: selectedPO.vendorId,
        vendorName: selectedPO.vendorName
      }));
    }
  };

  // Generate Bales action (5.2)
  const handleGenerateBales = () => {
    const count = Number(formData.totalBales) || 1;
    const existing = formData.bales || [];
    const newBales = [];

    const defaultFabricName = fabrics[0]?.qualityName || 'Grey Cotton Fabrics (100*100)';

    for (let i = 0; i < count; i++) {
      if (existing[i]) {
        newBales.push(existing[i]);
      } else {
        // Prepopulate with 17 pieces (reflecting client document packing slips)
        const initialPieceCount = 17;
        const initialPieces = [];
        for (let p = 1; p <= initialPieceCount; p++) {
          initialPieces.push({
            pieceNo: `Piece ${String(p).padStart(2, '0')}`,
            fabric: defaultFabricName,
            length: 104.0,
            remarks: 'Clean'
          });
        }

        newBales.push({
          baleNo: `Bale ${String(i + 1).padStart(2, '0')}`,
          piecesCount: initialPieceCount,
          totalLength: initialPieceCount * 104.0,
          pieces: initialPieces
        });
      }
    }

    setFormData((prev) => ({
      ...prev,
      bales: newBales,
      status: 'Bale Entry in Progress'
    }));
    setActiveBaleTab(0);
  };

  // Change Number of Pieces inside a Bale (5.2 & 8.3: Auto-generate piece rows without manual add row)
  const handlePieceCountChange = (baleIdx, newCount) => {
    const count = Math.max(1, Number(newCount) || 1);
    setFormData((prev) => {
      const updatedBales = [...prev.bales];
      const targetBale = { ...updatedBales[baleIdx] };
      const currentPieces = targetBale.pieces || [];
      const updatedPieces = [];

      const defaultFabricName = fabrics[0]?.qualityName || 'Grey Cotton Fabrics (100*100)';

      for (let p = 1; p <= count; p++) {
        if (currentPieces[p - 1]) {
          updatedPieces.push(currentPieces[p - 1]);
        } else {
          updatedPieces.push({
            pieceNo: `Piece ${String(p).padStart(2, '0')}`,
            fabric: defaultFabricName,
            length: '',
            remarks: ''
          });
        }
      }

      targetBale.piecesCount = count;
      targetBale.pieces = updatedPieces;
      targetBale.totalLength = updatedPieces.reduce((sum, it) => sum + (Number(it.length) || 0), 0);
      updatedBales[baleIdx] = targetBale;

      return { ...prev, bales: updatedBales };
    });
  };

  // Change length / quality / remarks for a specific piece
  const handlePieceChange = (baleIdx, pieceIdx, field, value) => {
    setFormData((prev) => {
      const updatedBales = [...prev.bales];
      const targetBale = { ...updatedBales[baleIdx] };
      const updatedPieces = [...targetBale.pieces];
      updatedPieces[pieceIdx] = { ...updatedPieces[pieceIdx], [field]: value };

      targetBale.pieces = updatedPieces;
      targetBale.totalLength = updatedPieces.reduce((sum, it) => sum + (Number(it.length) || 0), 0);
      updatedBales[baleIdx] = targetBale;

      return { ...prev, bales: updatedBales };
    });
  };

  // Live total sum of every piece length across all bales (5.2)
  const totalMetersEntered = (formData.bales || []).reduce(
    (total, bale) => total + (bale.totalLength || 0),
    0
  );

  // Mismatch calculation (5.2)
  const declaredTotal = Number(formData.declaredTotalMeters) || 0;
  const variance = Math.round((totalMetersEntered - declaredTotal) * 100) / 100;
  const isMismatch = Math.abs(variance) > 0.01;

  // Buffer calculation check against PO (5.2 & 8.3)
  const linkedPoRecords = purchaseOrders.filter((p) => formData.linkedPOs.includes(p.id));
  const totalOrderedQuantity = linkedPoRecords.reduce(
    (sum, p) => sum + p.items.reduce((iSum, it) => iSum + (Number(it.quantity) || 0), 0),
    0
  );
  const primaryPO = linkedPoRecords[0];
  const bufferAllowed = primaryPO?.bufferAllowed || false;
  const bufferPercent = Number(primaryPO?.bufferPercent) || 0;
  const allowedMax = totalOrderedQuantity * (1 + (bufferAllowed ? bufferPercent / 100 : 0));
  const allowedMin = totalOrderedQuantity * (1 - (bufferAllowed ? bufferPercent / 100 : 0));
  const isOutsideBuffer =
    totalOrderedQuantity > 0 && (totalMetersEntered > allowedMax || totalMetersEntered < allowedMin);

  // Auto-balance pieces helper (matches entered meters exactly with declared meters)
  const handleAutoBalancePieces = () => {
    if (!formData.bales || formData.bales.length === 0) return;
    const targetTotal = Number(formData.declaredTotalMeters) || 10415.25;
    const totalBalesCount = formData.bales.length;
    const perBaleTarget = targetTotal / totalBalesCount;

    const updatedBales = formData.bales.map((bale) => {
      const pCount = (bale.pieces || []).length || 1;
      const perPieceLen = Math.round((perBaleTarget / pCount) * 100) / 100;
      const updatedPieces = (bale.pieces || []).map((p, idx) => ({
        ...p,
        length: idx === pCount - 1 
          ? Math.round((perBaleTarget - (perPieceLen * (pCount - 1))) * 100) / 100 
          : perPieceLen
      }));
      return {
        ...bale,
        pieces: updatedPieces,
        totalLength: updatedPieces.reduce((sum, it) => sum + (Number(it.length) || 0), 0)
      };
    });

    setFormData((prev) => ({
      ...prev,
      bales: updatedBales
    }));
  };

  // Independent "Save Header" (5.2)
  const handleSaveHeaderOnly = () => {
    const payload = {
      ...formData,
      status: 'Header Saved',
      totalMetersEntered
    };
    if (onSaveGRN) {
      onSaveGRN(payload, false);
      alert('GRN Header saved successfully! Bale & piece entry can be resumed anytime.');
    }
  };

  // Final Submit / Complete GRN
  const handleCompleteGRN = (asDraft = false) => {
    // If saving as draft, allow anytime
    if (asDraft) {
      const payload = {
        ...formData,
        status: 'Draft',
        totalMetersEntered,
        adminApprovalNeeded: isOutsideBuffer
      };
      if (onSaveGRN) {
        onSaveGRN(payload, false);
        alert('GRN saved as Draft successfully! You can resume anytime.');
      }
      return;
    }

    // PDF 5.2 Rule: If mismatch occurs, prompt user or auto-balance
    if (isMismatch) {
      const proceed = confirm(
        `Piece-wise length total (${totalMetersEntered.toFixed(2)} Mtrs) does not match declared total (${declaredTotal.toFixed(2)} Mtrs).\n\nVariance: ${variance} Mtrs.\n\nClick OK to auto-balance and Complete GRN, or Cancel to review pieces manually.`
      );
      if (proceed) {
        handleAutoBalancePieces();
      } else {
        return;
      }
    }

    const payload = {
      ...formData,
      status: 'Completed',
      totalMetersEntered: isMismatch ? declaredTotal : totalMetersEntered,
      adminApprovalNeeded: isOutsideBuffer
    };

    if (onSaveGRN) {
      onSaveGRN(payload, true);
      alert(`GRN ${formData.id} Completed & Submitted successfully!\nQC Record generated automatically.`);
    }
  };

  const currentBale = formData.bales[activeBaleTab] || formData.bales[0];

  return (
    <div className="container-fluid p-0">
      {/* Top Header */}
      <div className="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4">
        <div className="d-flex align-items-center gap-3">
          <button
            type="button"
            className="btn btn-light rounded-circle p-2 d-flex align-items-center justify-content-center"
            style={{ width: '40px', height: '40px' }}
            onClick={onBack}
          >
            <i className="ti ti-arrow-left fs-18"></i>
          </button>
          <div>
            <div className="d-flex align-items-center gap-2">
              <h3 className="fw-bold text-dark mb-0 fs-20">
                {isExisting ? `Goods Receipt Note ${formData.id}` : 'Create Goods Receipt Note (GRN)'}
              </h3>
              <span
                className={`badge px-2 py-1 fs-12 ${
                  formData.status === 'Completed'
                    ? 'bg-success-subtle text-success'
                    : 'bg-primary-subtle text-primary'
                }`}
              >
                {formData.status}
              </span>
            </div>
            <p className="text-secondary mb-0 fs-13">
              3-Level Physical Goods Inward (Header → Bale → Piece Meter Entry)
            </p>
          </div>
        </div>

        <div className="d-flex align-items-center gap-2">
          <button
            type="button"
            className="btn btn-outline-secondary px-3 py-2 fw-medium fs-13 rounded-3"
            onClick={handleSaveHeaderOnly}
          >
            <i className="ti ti-device-floppy me-1"></i>
            <span>Save Header Only</span>
          </button>

          <button
            type="button"
            className="btn btn-light px-3 py-2 fw-medium fs-13 rounded-3"
            onClick={() => handleCompleteGRN(true)}
          >
            Save Draft
          </button>

          <button
            type="button"
            className="btn btn-success d-flex align-items-center gap-2 px-4 py-2 fw-medium fs-13 rounded-3 shadow-sm"
            onClick={() => handleCompleteGRN(false)}
          >
            <i className="ti ti-circle-check fs-16"></i>
            <span>Complete &amp; Submit GRN</span>
          </button>
        </div>
      </div>

      {/* LEVEL 1: GRN HEADER CARD */}
      <div className="card border-0 shadow-sm rounded-4 p-4 mb-4 bg-white">
        <div className="d-flex align-items-center justify-content-between mb-3 border-bottom pb-2">
          <div className="d-flex align-items-center gap-2">
            <span className="badge bg-primary rounded-pill px-2 py-1 fs-11">Level 1</span>
            <h5 className="fw-bold text-dark mb-0 fs-16">GRN Header Information</h5>
          </div>
        </div>

        <div className="row g-3">
          {/* Linked POs Multi-Select (8.3: restricted to same vendor) */}
          <div className="col-12 col-md-6">
            <label className="form-label fs-12 fw-semibold mb-1">
              Linked Purchase Order(s) * (Multi-PO for same vendor supported)
            </label>
            <div className="d-flex flex-wrap gap-2 p-2 bg-light rounded-3 border">
              {availablePOs.length === 0 ? (
                <span className="text-muted fs-12 p-1">No pending POs waiting for delivery.</span>
              ) : (
                availablePOs.map((po) => {
                  const isSelected = formData.linkedPOs.includes(po.id);
                  return (
                    <button
                      key={po.id}
                      type="button"
                      className={`btn btn-sm d-flex align-items-center gap-1 rounded-pill px-3 py-1 ${
                        isSelected ? 'btn-primary shadow-sm' : 'btn-outline-secondary bg-white'
                      }`}
                      onClick={() => handleTogglePO(po.id)}
                    >
                      <span className="fw-semibold">{po.id}</span>
                      <span className="opacity-75 fs-11">({po.vendorName.split(' ')[0]})</span>
                      {isSelected && <i className="ti ti-check fs-12"></i>}
                    </button>
                  );
                })
              )}
            </div>
            <div className="form-text fs-11 text-muted">
              Auto-fills vendor and matches buffer tolerances.
            </div>
          </div>

          {/* Vendor */}
          <div className="col-12 col-md-3">
            <label className="form-label fs-12 fw-semibold mb-1">Vendor (Auto-Filled)</label>
            <div className="p-2 bg-light rounded-2 border fw-bold text-dark fs-13">
              {formData.vendorName || 'No Vendor Linked'}
            </div>
          </div>

          {/* Transporter with Inline New */}
          <div className="col-12 col-md-3">
            <div className="d-flex align-items-center justify-content-between mb-1">
              <label className="form-label fs-12 fw-semibold mb-0">Transporter</label>
              <button
                type="button"
                className="btn btn-link btn-sm p-0 text-primary fs-11 text-decoration-none"
                onClick={() => setShowInlineTransporterModal(true)}
              >
                + New
              </button>
            </div>
            <select
              className="form-select form-select-sm bg-light fs-13"
              value={formData.transporterId}
              onChange={(e) => {
                const trn = transporters.find((t) => t.id === e.target.value);
                setFormData({
                  ...formData,
                  transporterId: e.target.value,
                  transporterName: trn ? trn.name : ''
                });
              }}
            >
              {transporters.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.name}
                </option>
              ))}
            </select>
          </div>

          {/* Invoices and Challans */}
          <div className="col-6 col-md-3">
            <label className="form-label fs-12 fw-semibold mb-1">Vendor Invoice No.</label>
            <input
              type="text"
              placeholder="e.g. MST/1360/26-27"
              className="form-control form-control-sm bg-light fs-13"
              value={formData.vendorInvoiceNo}
              onChange={(e) => setFormData({ ...formData, vendorInvoiceNo: e.target.value })}
            />
          </div>

          <div className="col-6 col-md-3">
            <label className="form-label fs-12 fw-semibold mb-1">Vendor Invoice Date</label>
            <input
              type="date"
              className="form-control form-control-sm bg-light fs-13"
              value={formData.vendorInvoiceDate}
              onChange={(e) => setFormData({ ...formData, vendorInvoiceDate: e.target.value })}
            />
          </div>

          <div className="col-6 col-md-3">
            <label className="form-label fs-12 fw-semibold mb-1">Vendor Challan No.</label>
            <input
              type="text"
              placeholder="e.g. 1360"
              className="form-control form-control-sm bg-light fs-13"
              value={formData.vendorChallanNo}
              onChange={(e) => setFormData({ ...formData, vendorChallanNo: e.target.value })}
            />
          </div>

          <div className="col-6 col-md-3">
            <label className="form-label fs-12 fw-semibold mb-1">Vendor Challan Date</label>
            <input
              type="date"
              className="form-control form-control-sm bg-light fs-13"
              value={formData.vendorChallanDate}
              onChange={(e) => setFormData({ ...formData, vendorChallanDate: e.target.value })}
            />
          </div>

          {/* Total Bales & Declared Meters */}
          <div className="col-12 col-md-4">
            <label className="form-label fs-12 fw-semibold mb-1">Total Number of Bales *</label>
            <div className="input-group input-group-sm">
              <input
                type="number"
                min="1"
                placeholder="e.g. 5"
                className="form-control form-control-sm bg-light no-spinner fs-13"
                value={formData.totalBales}
                onChange={(e) => setFormData({ ...formData, totalBales: e.target.value })}
              />
              <button
                type="button"
                className="btn btn-primary d-flex align-items-center gap-1 px-3"
                onClick={handleGenerateBales}
              >
                <i className="ti ti-layout-grid-add fs-14"></i>
                <span>Generate Bales</span>
              </button>
            </div>
            <div className="form-text fs-11 text-muted">
              Clicking button generates individual bale cards below.
            </div>
          </div>

          <div className="col-12 col-md-4">
            <label className="form-label fs-12 fw-semibold mb-1">
              Declared Total Quantity Received (Mtrs) *
            </label>
            <input
              type="number"
              step="0.01"
              placeholder="e.g. 10415.25"
              className="form-control form-control-sm bg-light no-spinner fs-13"
              value={formData.declaredTotalMeters}
              onChange={(e) => setFormData({ ...formData, declaredTotalMeters: e.target.value })}
            />
          </div>

          {/* Running Totals & Mismatch Box */}
          <div className="col-12 col-md-4">
            <div className="p-3 bg-light rounded-3 border">
              <div className="d-flex align-items-center justify-content-between mb-1">
                <span className="fs-12 text-secondary">Sum of Pieces Entered:</span>
                <strong
                  className={`fs-14 ${
                    isMismatch ? 'text-danger fw-bold' : 'text-success fw-bold'
                  }`}
                >
                  {totalMetersEntered.toFixed(2)} Mtrs
                </strong>
              </div>

              <div className="d-flex align-items-center justify-content-between fs-12">
                <span className="text-secondary">Declared vs Entered:</span>
                {isMismatch ? (
                  <div className="d-flex align-items-center gap-2">
                    <span className="badge bg-danger-subtle text-danger">
                      Mismatch: {variance > 0 ? `+${variance}` : variance} Mtrs
                    </span>
                    <button
                      type="button"
                      className="btn btn-xs btn-outline-primary py-0 px-2 rounded-pill fs-11 fw-semibold"
                      onClick={handleAutoBalancePieces}
                      title="Automatically distribute pieces to match declared total exactly"
                    >
                      ⚡ Auto-Balance
                    </button>
                  </div>
                ) : (
                  <span className="badge bg-success-subtle text-success">Balanced (100% Match)</span>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Buffer Tolerance Flag Alert (5.2 & 8.3) */}
        {isOutsideBuffer && (
          <div className="alert alert-warning d-flex align-items-center gap-2 mb-0 mt-3 fs-13">
            <i className="ti ti-alert-triangle fs-18"></i>
            <div>
              <strong>Tolerance Exceeded:</strong> Total received meters ({totalMetersEntered.toFixed(2)}{' '}
              Mtrs) is outside the PO buffer limit (±{bufferPercent}%). Excess quantity cannot enter
              the main Stock Pool without Admin variance approval and justification.
            </div>
          </div>
        )}
      </div>

      {/* LEVEL 2 & 3: BALE ENTRY & PIECE-WISE METER MATRIX */}
      <div className="card border-0 shadow-sm rounded-4 p-4 bg-white">
        <div className="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-3 border-bottom pb-2">
          <div className="d-flex align-items-center gap-2">
            <span className="badge bg-primary rounded-pill px-2 py-1 fs-11">Level 2 &amp; 3</span>
            <h5 className="fw-bold text-dark mb-0 fs-16">
              Bales &amp; Piece-Wise Meter Entry (Packing Slip Level)
            </h5>
          </div>

          <div className="d-flex align-items-center gap-2">
            <span className="text-muted fs-12">Bale Count:</span>
            <span className="badge bg-light text-dark border px-2 py-1">
              {(formData.bales || []).length} Bales Created
            </span>
          </div>
        </div>

        {(formData.bales || []).length === 0 ? (
          <div className="text-center py-5 text-muted">
            <i className="ti ti-package-off fs-40 d-block mb-2"></i>
            <h6 className="fw-semibold">No Bales Generated Yet</h6>
            <p className="fs-13">
              Enter the "Total Number of Bales" on the header above and click <strong>Generate Bales</strong>.
            </p>
          </div>
        ) : (
          <div>
            {/* Bale Tabs Pill Switcher */}
            <div className="d-flex flex-wrap align-items-center gap-2 mb-4 pb-2 border-bottom">
              {formData.bales.map((bale, idx) => (
                <button
                  key={idx}
                  type="button"
                  className={`btn btn-sm rounded-pill px-3 py-1 d-flex align-items-center gap-2 fs-12 ${
                    activeBaleTab === idx
                      ? 'btn-primary shadow-sm'
                      : 'btn-outline-secondary bg-white'
                  }`}
                  onClick={() => setActiveBaleTab(idx)}
                >
                  <span className="fw-bold">{bale.baleNo.split(' ')[0]} {bale.baleNo.split(' ')[1]}</span>
                  <span
                    className={`badge rounded-pill ${
                      activeBaleTab === idx ? 'bg-white text-primary' : 'bg-light text-secondary'
                    }`}
                  >
                    {(bale.totalLength || 0).toFixed(1)}m
                  </span>
                </button>
              ))}
            </div>

            {/* Active Bale Card Details */}
            {currentBale && (
              <div className="p-3 bg-light rounded-3 mb-4">
                <div className="row g-3 align-items-center mb-3">
                  <div className="col-12 col-md-4">
                    <h5 className="fw-bold text-primary mb-0 fs-16">{currentBale.baleNo}</h5>
                    <div className="text-muted fs-11">
                      Packing slip meter recording for this container
                    </div>
                  </div>

                  {/* Number of Pieces in this Bale (5.2: auto generates piece rows immediately) */}
                  <div className="col-12 col-md-4">
                    <div className="d-flex align-items-center gap-2">
                      <label className="form-label fs-12 fw-semibold mb-0 text-nowrap">
                        Pieces in this Bale *:
                      </label>
                      <input
                        type="number"
                        min="1"
                        placeholder="17"
                        className="form-control form-control-sm bg-white no-spinner text-center fs-13 fw-bold"
                        style={{ width: '80px' }}
                        value={currentBale.piecesCount || ''}
                        onChange={(e) => handlePieceCountChange(activeBaleTab, e.target.value)}
                      />
                    </div>
                    <div className="form-text fs-10 text-muted">
                      Typing count automatically generates piece rows.
                    </div>
                  </div>

                  <div className="col-12 col-md-4 text-end">
                    <span className="fs-12 text-secondary d-block">Bale Total Meters:</span>
                    <span className="fw-bold text-dark fs-18">
                      {(currentBale.totalLength || 0).toFixed(2)} Mtrs
                    </span>
                  </div>
                </div>

                {/* Level 3: Pieces Grid (Packing Slips) */}
                <div className="card bg-white border-0 shadow-sm rounded-3 p-3">
                  <div className="table-responsive" style={{ maxHeight: '420px' }}>
                    <table className="table table-sm table-hover align-middle mb-0 fs-13">
                      <thead className="table-light text-secondary sticky-top">
                        <tr>
                          <th style={{ width: '12%' }}>Piece No.</th>
                          <th style={{ width: '45%' }}>Fabric Quality *</th>
                          <th style={{ width: '23%' }} className="text-end">
                            Piece Length / Mtrs *
                          </th>
                          <th style={{ width: '20%' }}>Remarks</th>
                        </tr>
                      </thead>
                      <tbody>
                        {(currentBale.pieces || []).map((piece, pIdx) => (
                          <tr key={pIdx}>
                            <td className="fw-bold text-secondary font-monospace">
                              {piece.pieceNo}
                            </td>
                            <td>
                              <select
                                className="form-select form-select-sm bg-light fs-12"
                                value={piece.fabric}
                                onChange={(e) =>
                                  handlePieceChange(
                                    activeBaleTab,
                                    pIdx,
                                    'fabric',
                                    e.target.value
                                  )
                                }
                              >
                                {fabrics.map((f) => (
                                  <option key={f.id} value={f.qualityName}>
                                    {f.qualityName}
                                  </option>
                                ))}
                              </select>
                            </td>
                            <td className="text-end">
                              <input
                                type="number"
                                step="0.25"
                                placeholder="e.g. 104.50"
                                className="form-control form-control-sm bg-light text-end fs-13 fw-semibold no-spinner"
                                value={piece.length}
                                onChange={(e) =>
                                  handlePieceChange(
                                    activeBaleTab,
                                    pIdx,
                                    'length',
                                    e.target.value
                                  )
                                }
                              />
                            </td>
                            <td>
                              <input
                                type="text"
                                placeholder="Clean / Cut"
                                className="form-control form-control-sm bg-light fs-12"
                                value={piece.remarks}
                                onChange={(e) =>
                                  handlePieceChange(
                                    activeBaleTab,
                                    pIdx,
                                    'remarks',
                                    e.target.value
                                  )
                                }
                              />
                            </td>
                          </tr>
                        ))}
                      </tbody>
                      <tfoot className="table-light">
                        <tr>
                          <td colSpan="2" className="fw-bold text-end fs-13">
                            {currentBale.baleNo} Sub-Total:
                          </td>
                          <td className="text-end fw-bold text-primary fs-14">
                            {(currentBale.totalLength || 0).toFixed(2)} Mtrs
                          </td>
                          <td></td>
                        </tr>
                      </tfoot>
                    </table>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Inline Modal for Transporter Master */}
      {showInlineTransporterModal && (
        <div className="modal show d-block" style={{ background: 'rgba(0,0,0,0.5)', zIndex: 1060 }}>
          <div className="modal-dialog modal-lg modal-dialog-centered">
            <div className="modal-content border-0 shadow-lg rounded-4 p-3">
              <TransporterMasterView
                transporters={transporters}
                isInline={true}
                onCloseInline={(newCreatedTrn) => {
                  if (newCreatedTrn) {
                    setFormData((prev) => ({
                      ...prev,
                      transporterId: newCreatedTrn.id,
                      transporterName: newCreatedTrn.name
                    }));
                  }
                  setShowInlineTransporterModal(false);
                }}
              />
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
